# setup:
#   addons:
#     - plan: heroku-postgresql
#       as: DATABASE
# build:
#   docker:
#     web: mymeds/Dockerfile
# release:
#   image: web
#   command:
#     - ./test.sh

build:
  docker:
    web: Dockerfile
    worker: worker/Dockerfile
release:
  image: worker
  command:
    - ./test.sh